# WARNING: Changing SQL settings while the server is running may lead to some funky results.
# You have been warned.
# This should be true unless you know waht you're doing
# Recommended value: true
useSQLite: true

# The path to save state data to if the above option is set to true
# Both relative and absolute paths are accepted
# Recommended value: "data.sqlite"
sqlitePath: "data.sqlite"

# You only need to fill in this data if you are using an SQL server
# and the above option is set to false
SQL:
  host: ""
  port: 33333
  database: ""
  username: ""
  password: ""

# Whether the results of any config parsing should be printed to the console
# Useful for debugging but fills the console up quickly with larger config files
# Errors will be prined regardless of this setting
# Recommended value: false
verboseLogging: false

# This is the priority given to all triggers where a priority isn't explicitly stated
# You shouldn't usually need to change this
# Recommended value: 500
defaultTriggerPriority: 500

# The range at which conversations stop when players walk away
# This can be set per NPC through the NPC's config file in Citizens2,
# or set back to this value with -1.
# Disable conversations stopping by setting this value to -1
# Recommended value: 5
defaultConversationMaxRange: 5

# A smaller value here makes some aspects of conversations more responsive, but
# also creates more lag.
# Recommended value: 15 in normal cases, 5 for very few NPCs, 30+ for many NPCs
ticksPerRangeCheck: 15

# The default speed of text when a speed isn't given inside of a script
# Default value: 0.7
defaultTextSpeed: 0.7

# The number of characters to display before a line break if a line break isn't
# manually placed
# Default value: 20
charactersPerLine: 20

# The string that should be placed at the start of every new line. This is usually a
# colour code but can be any text
# Default value: §7
lineStartString: §7

# The global triggers, visible from any role
triggers:
  walkClose:
    type: playermove
    prerequisites:
      range: 5
      
# The set of roles
roles: