name: RPGNPCs
main: rpg_npcs.RPGNPCsPlugin
version: 0.0.1
api-version: 1.13
depend: [Citizens, HolographicDisplays]
softdepend: [PlaceholderAPI, Shop, Magic]
commands:
   calculate:
      description: Resolves a given expression to a value
      usage: /calcuate <expression>
      aliases: calc
      permission: RPGNPCs.calculate
      permission-message: You don't have permission to do that
   rpgnpc:
      description: Base command for most actions
      usage: /rpgnpc <subcommand>
      aliases: rpgnpcs
      permission: RPGNPCs.edit
      permission-message: You don't have permission to do that